[features]
seeds = false
[programs.devnet]
first_solana_project = "DsvhEL6cuoSZaDnUxvSx1FEpfPS9MAAhtKfJpc6xWQY1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/andrewgarcia/.config/solana/id.json"

[scripts]
test = "node tests/first-solana-project.js"
